services:
  db:
    image: postgres:15
    container_name: pvz_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pvz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5

  migrate:
    image: migrate/migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/pvz?sslmode=disable",
      "up"
    ]
    restart: on-failure

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pvz_server
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      migrate:
        condition: service_completed_successfully
    restart: unless-stopped
    volumes:
      - .:/app

volumes:
  postgres_data:
